from typing import Protocol, runtime_checkable

from k_pilot.core.domain import Result, WindowInfo


@runtime_checkable
class WindowManagerPort(Protocol):
    """Puerto para gestión de ventanas del entorno gráfico."""

    async def list_windows(self) -> list[WindowInfo]: ...
    async def get_active_window(self) -> WindowInfo | None: ...

    async def focus_window(self, window_id: str) -> Result: ...
    async def close_window(self, window_id: str) -> Result: ...
    async def minimize_window(self, window_id: str) -> Result: ...
    async def maximize_window(self, window_id: str) -> Result: ...

    def is_available(self) -> bool: ...
