from typing import Any, Protocol


class PropertiesProxy(Protocol):
    """Protocol for D-Bus Properties interface."""

    def Get(self, interface: str, property: str) -> Any: ...
    def Set(self, interface: str, property: str, value: Any) -> None: ...


class PlayerProxy(Protocol):
    """Protocol for MPRIS Player interface."""

    def Play(self) -> None: ...
    def Pause(self) -> None: ...
    def PlayPause(self) -> None: ...
    def Next(self) -> None: ...
    def Previous(self) -> None: ...
    def Stop(self) -> None: ...
    def Seek(self, offset: int) -> None: ...
    def SetPosition(self, track_id: str, position: int) -> None: ...


class DbusProxy(Protocol):
    """Protocol for D-Bus daemon interface."""

    def ListNames(self) -> list[str]: ...
