from typing import Protocol, runtime_checkable

from k_pilot.core.domain import MediaInfo, MediaPlayer, Notification, RepeatMode, Result, WindowInfo


@runtime_checkable
class WindowManagerPort(Protocol):
    """Puerto para gestión de ventanas del entorno gráfico."""

    async def list_windows(self) -> list[WindowInfo]: ...
    async def get_active_window(self) -> WindowInfo | None: ...

    async def focus_window(self, window_id: str) -> Result: ...
    async def close_window(self, window_id: str) -> Result: ...
    async def minimize_window(self, window_id: str) -> Result: ...
    async def maximize_window(self, window_id: str) -> Result: ...

    def is_available(self) -> bool: ...


@runtime_checkable
class MediaControlPort(Protocol):
    """Puerto de control multimedia basado en MPRIS2."""

    # ===== Control básico =====
    async def toggle_playback(self, player_name: str | None = None) -> Result: ...
    async def next_track(self, player_name: str | None = None) -> Result: ...
    async def previous_track(
        self, force: bool = False, player_name: str | None = None
    ) -> Result: ...
    async def stop(self, player_name: str | None = None) -> Result: ...

    # ===== Seek y posición =====
    async def seek(self, position_ms: int, player_name: str | None = None) -> Result:
        """Realiza seek absoluto a `position_ms` milisegundos."""
        ...

    async def skip_forward(self, offset_ms: int = 10000, player_name: str | None = None) -> Result:
        """Adelanta `offset_ms` milisegundos."""
        ...

    async def skip_backward(self, offset_ms: int = 10000, player_name: str | None = None) -> Result:
        """Retrocede `offset_ms` milisegundos."""
        ...

    # ===== Modos de reproducción =====
    async def get_repeat_mode(self, player_name: str | None = None) -> RepeatMode: ...
    async def set_repeat_mode(self, mode: RepeatMode, player_name: str | None = None) -> Result: ...

    async def cycle_repeat_mode(self, player_name: str | None = None) -> Result:
        """Rota entre NONE -> TRACK -> PLAYLIST -> NONE."""
        ...

    async def toggle_shuffle(self, player_name: str | None = None) -> Result: ...

    # ===== Volumen =====
    async def set_volume(self, volume: float, player_name: str | None = None) -> Result:
        """Ajusta el volumen en el rango 0.0 a 1.0."""
        ...

    # ===== Info =====
    async def get_current_track(self, player_name: str | None = None) -> MediaInfo | None: ...
    async def list_players(self) -> list[MediaPlayer]: ...

    def is_available(self) -> bool: ...


@runtime_checkable
class NotificationPort(Protocol):
    """Puerto para envío de notificaciones del sistema."""

    def send(self, notification: Notification) -> Result: ...
    def is_available(self) -> bool: ...
