"""Puertos (interfaces) del dominio."""

from typing import Protocol, runtime_checkable

from .models import (
    MediaInfo,
    MediaPlayer,
    Notification,
    RepeatMode,
    Result,
    ShuffleMode,
    WindowInfo,
)


@runtime_checkable
class NotificationPort(Protocol):
    def send(self, notification: Notification) -> Result: ...
    def is_available(self) -> bool: ...


@runtime_checkable
class WindowManagerPort(Protocol):
    async def list_windows(self) -> list[WindowInfo]: ...
    def focus_window(self, window_id: str) -> Result: ...
    def minimize_window(self, window_id: str) -> Result: ...
    def maximize_window(self, window_id: str) -> Result: ...
    def close_window(self, window_id: str) -> Result: ...
    def get_active_window(self) -> WindowInfo | None: ...
    def is_available(self) -> bool: ...


@runtime_checkable
class MediaControlPort(Protocol):
    """
    MPRIS2 completo: play, seek, repeat, shuffle, volumen.
    """

    # ===== Control básico =====
    async def play_pause(self) -> Result: ...
    async def next_track(self) -> Result: ...
    async def previous_track(self, force: bool = False) -> Result: ...
    async def stop(self) -> Result: ...

    # ===== Seek y posición =====
    async def seek(self, position_ms: int) -> Result:
        """Seek absoluto a position_ms (milisegundos)."""
        ...

    async def skip_forward(self, offset_ms: int = 10000) -> Result:
        """Adelantar offset_ms (default 10s)."""
        ...

    async def skip_backward(self, offset_ms: int = 10000) -> Result:
        """Retroceder offset_ms (default 10s)."""
        ...

    # ===== Modos de reproducción =====
    async def get_repeat_mode(self) -> RepeatMode: ...

    async def set_repeat_mode(self, mode: RepeatMode) -> Result: ...

    async def cycle_repeat_mode(self) -> Result:
        """Rota: None -> Track -> Playlist -> None."""
        ...

    async def toggle_shuffle(self) -> Result: ...

    # ===== Volumen =====
    async def set_volume(self, volume: float) -> Result:
        """volume: 0.0 a 1.0."""
        ...

    # ===== Info =====
    async def get_current_track(self) -> MediaInfo | None: ...
    async def list_players(self) -> list[MediaPlayer]: ...
    def is_available(self) -> bool: ...
